### ISSUE TITLE
HTTP API - dsort

### ISSUE THREAD

**Issue by mike-gee** [NVIDIA/aistore#103]
The documentation [here](https://github.com/NVIDIA/aistore/blob/master/docs/http_api.md) suggests that dsort can be accessed via `v1/dsort`.

However, it seems to be the case that it is instead accessed via `v1/sort`.

**Comment by mike-gee** [comment]
The [examples](https://github.com/NVIDIA/aistore/blob/master/docs/http_api.md#cluster-operations) for other resources like `cluster` and `buckets` are extremely helpful. 

Happy to help put together some examples for `sort` / `dsort` as well.

**Comment by alex-aizman** [comment]
[updated](https://github.com/NVIDIA/aistore/commit/7887fff3fa69e0b1b546c2f3d0f216dc6d32b4e0) - thank you. 

Help with `dsort` examples will be extremely appreciated!
