### ISSUE TITLE
Support mountable POSIX files-system

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/aistore#108]
Are there plans to support the aistore as a mountable POSIX file-system?

Or any experiences using https://github.com/kahing/goofys or https://github.com/s3fs-fuse/s3fs-fuse

Use case: ease object store migration for data loaders that still reads via posix

**Comment by VirrageS** [comment]
There is already FUSE implementation to mount AIStore as directory. Please refer to https://aiatscale.org/docs/aisfs.

**Comment by eugeneteoh** [comment]
@VirrageS Can you point me to the docs about the FUSE implementation? The link you referred no longer works, and I can't find much from searching.
