### ISSUE TITLE
Question on AIStore cluster metrics

### ISSUE THREAD

**Issue by KavyaPuranik** [NVIDIA/aistore#109]
Hi,

How do I collect the metrics of ais-node application that is deployed using ais-operator style? Is it similar to the helm chart way? If not, can we have a doc on that please.

**Comment by alex-aizman** [comment]
* [docs/prometheus.md](https://github.com/NVIDIA/aistore/blob/master/docs/prometheus.md)
* [docs/metrics.md](https://github.com/NVIDIA/aistore/blob/master/docs/prometheus.md)

This was written at different times ("prometheus" more recently), and so there's a bit of an overlap. 

The same is also visible via https://aiatscale.org/docs (see "Observability").

In the sources, most of the variables are statically named and listed in one of these:

* https://github.com/NVIDIA/aistore/blob/master/stats/common_stats.go#L74-L99
* https://github.com/NVIDIA/aistore/blob/master/stats/target_stats.go#L32-L75
* https://github.com/NVIDIA/aistore/blob/master/xact/stats.go#L26-L33

**Comment by KavyaPuranik** [comment]
Thank you!
