### ISSUE TITLE
Retrieval Cost for AIS with GCP / AWS 

### ISSUE THREAD

**Issue by HHenryD** [NVIDIA/aistore#112]
I am interested in using PT+AIS to iterate over Google Cloud buckets using the Iterable DataPipes API in PT 1.12, and was wondering if there were retrieval costs in using AIS. Aside from paying for the storage, how cost-friendly would it be to use AIS+Google Cloud (or other services like Webdataset) for training over long durations?

**Comment by gaikwadabhishek** [comment]
Assuming you will use [AISFileLister](https://pytorch.org/data/main/generated/torchdata.datapipes.iter.AISFileLister.html#torchdata.datapipes.iter.AISFileLister) and loads [AISFileLoader](https://pytorch.org/data/main/generated/torchdata.datapipes.iter.AISFileLoader.html#torchdata.datapipes.iter.AISFileLoader).

 With AIS in front of your Cloud bucket(s), you save both cost and time as AIS issues cold GET requests only once on a per-object basis. Multiple alternative [data pre-loading](https://github.com/NVIDIA/aistore/blob/master/docs/overview.md#existing-datasets) mechanisms are also supported. Users can store data according to the per-bucket configurable policies (erasure coding, LRU, etc.).

![Screen Shot 2022-09-23 at 11 57 36 AM](https://user-images.githubusercontent.com/26243594/192038210-7ce3056c-ef98-4c77-af17-0287f33c1a31.png)
