### ISSUE TITLE
ModuleNotFoundError: No module named 'aistore.botocore_patch'

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/aistore#117]
Hi, I was attempting to test the example here:
https://github.com/NVIDIA/aistore/blob/master/docs/s3compat.md#boto3-compatibility

I installed the library with `%pip install aistore[botocore]`, however the import fails:

`from aistore.botocore_patch import botocore`

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 2
      1 import boto3
----> 2 from aistore.botocore_patch import botocore

ModuleNotFoundError: No module named 'aistore.botocore_patch'
```

**Comment by straill-nvidia** [comment]
Hi @austinmw  - I'm sorry; it looks like those docs ran ahead of the pypi package.

[We've just pushed the SDK release](https://github.com/NVIDIA/aistore/commit/344105a85db1afe6600d3f70abb8e16564f4792c) that should be in step with them. If you upgrade to python SDK 1.0.5 (or newer) your import should work as documented now, I think. Let us know how you get on.

```
$ pip install aistore[botocore]==1.0.5
$ python -c 'from aistore.botocore_patch import botocore'
$
```

**Comment by austinmw** [comment]
Thanks!
