### ISSUE TITLE
E 06:05:56.448375 target.go:258 FATAL ERROR: operation not supported

### ISSUE THREAD

**Issue by sc-kevin** [NVIDIA/aistore#123]
Hi,

When trying to spin up a container by the following command:
```
docker run -d \
           -p 51080:51080 \
           -v /nvme/disk0:/ais/disk0 \
           aistore/cluster-minimal:latest
```
the container automatically shuts down immediately. The error upon `docker logs` is:
```
E 06:05:56.448375 target.go:258 FATAL ERROR: operation not supported
FATAL ERROR: operation not supported
```

However, if use `-v /disk0:/ais/disk0`, the spin up is successful.

The `FSTYPE` difference between `/nvme/disk0` and `/disk0` are:
`/nvme/disk0` `nfs`
`/disk0` `ext4`

Is it because something is not supported in `nfs` type?

Thanks !

**Comment by VirrageS** [comment]
Hey @sc-kevin sorry for late response. The issue most likely is that NFS doesn't support extended attributes which are required by aistore.

**Comment by alex-aizman** [comment]
won't be providing a workaround any time soon - closing
