### ISSUE TITLE
Does not support GPU direct Storage now 

### ISSUE THREAD

**Issue by superleo** [NVIDIA/aistore#129]
I walked throught the doc and also searched in the code. Cannot find GDS support information. Which may important for an AI Storage. Do we have plan to implement it?

**Comment by alex-aizman** [comment]
No plans today but may change given popular demand. Safe to say though, there will be no GPUDirect integration between now and Sept/Oct timeframe.

**Comment by superleo** [comment]
any suggestion if I want to do sth on GDS support for aistore? @alex-aizman 
Need to support GDR first, right?

**Comment by alex-aizman** [comment]
not an issue for aistore - closing
