### ISSUE TITLE
bin installer does not exist

### ISSUE THREAD

**Issue by superleo** [NVIDIA/aistore#131]
try to get aisfs or aisloader binary from below as mentioned in doc. received 404 error:

https://raw.githubusercontent.com/NVIDIA/aistore/master/cmd/bin_installer.sh

**Comment by VirrageS** [comment]
Thanks for the issue! Seems like we missed updating the documentation when we removed the script.

To install `aisfs` or `aisloader` binaries you can use `go install github.com/NVIDIA/aistore/cmd/aisfs@latest` and `go install github.com/NVIDIA/aistore/cmd/aisloader@latest` respectively.

We will update the documentation soon :)

**Comment by superleo** [comment]
I'm wonderring if go install can replace the binary release. Go install need golang env and it download code and build and then install.   It may not easier than to make it in my dev env first and copy it to destination env. 

I mean, deliver binary release is better than provide go install command in doc.

**Comment by VirrageS** [comment]
That's fair point. Currently we don't do binary releases but I agree it would be much easier to distributed/install/download than invoking `go install` command. We will try to improve this process.

**Comment by alex-aizman** [comment]
updated
