### ISSUE TITLE
Can you please rebuild the Docker image `aistorage/ais-operator:0.94`?

### ISSUE THREAD

**Issue by yingca1** [NVIDIA/aistore#133]
The latest version of ais-operator:v0.94 (https://github.com/NVIDIA/ais-k8s/releases/download/v0.94/ais-operator.yaml) requires aistorage/ais-operator:0.94. 

However, I noticed that the build job for the docker image `aistorage/ais-operator` failed (https://github.com/NVIDIA/ais-k8s/actions/runs/4601654066/jobs/8130027662) and the image cannot be found on the docker repository (https://hub.docker.com/r/aistorage/ais-operator/tags).

To address this issue, I have forked the `NVIDIA/ais-k8s` repository and successfully built version v0.94. You can check the successful build here (https://github.com/yingca1/ais-k8s/actions/runs/5281905587/jobs/9556105528). I kindly request that you rebuild `aistorage/ais-operator:0.94`.

As `NVIDIA/ais-k8s` does not have issue tracking enabled, I am posting this issue here.

**Comment by saiprashanth173** [comment]
@yingca1 thanks for raising this issue. We pushed the  `aistorage/ais-operator:0.94` image. Please let us know if you face any issue with the latest image.
