### ISSUE TITLE
aistore.sdk.errors.AISError: STATUS:404, MESSAGE:x-[emL1D2Xudc] not found (jhNp8080(*)) This exception is thrown by __iter__ of AISFileListerIterDataPipe(length=-1, source_datapipe=['ais://OB_static'])

### ISSUE THREAD

**Issue by VCBE123** [NVIDIA/aistore#156]

**Comment by gaikwadabhishek** [comment]
Hey @VCBE123 , 
This might occur when you are trying to get an object that doesn't exist or if you are listing on the wrong bucket. Can you please give me some more information on what you are trying to do and the cluster that is running?
