### ISSUE TITLE
Use more reliable way to validate backend disk of mountpath

### ISSUE THREAD

**Issue by and-1** [NVIDIA/aistore#158]
I have few disks on each node for data. Sometimes when system reboot disk name has changed (e.x. was /dev/sdd become /dev/sdb). Mountpath and disk binding the same as before, but with new disk name. This situation unexpected for ais target and it does not start with error:
`[storage integrity error sie#50, for troubleshooting see https://github.com/NVIDIA/aistore/blob/master/docs/troubleshooting.md]: lost or missing mountpath "/ais/sdc" ({Fs:/dev/sdb FsType:xfs FsID:2064,0
} vs {Path:/ais/sdc Fs:/dev/sdd FsType:xfs FsID:2096,0 Ext:<nil> Enabled:true})`

/dev/sd[a-z] not reliable reference to disk. I think more correct way to use /dev/disk/by-id/* or /dev/disk/by-uuid/* to bind disk to mountpath

**Comment by alex-aizman** [comment]
can you provide logs - e.g.:

```console
$ ais log get cluster
```

and attach all of them

**Comment by and-1** [comment]
Now my target pods up and running, but I attached logs with problem received by kubectl logs -p \<pod\>
[ais-target.tar.gz](https://github.com/NVIDIA/aistore/files/13419480/ais-target.tar.gz)

JFYI: I attach data to target pods using pv and local static provisioner. PV created by hand and seems like that:
```
apiVersion: v1
kind: PersistentVolume
spec:
  local:
    fsType: xfs
    path: /dev/disk/by-id/wwn-0x5002538e7210943e
...
```

**Comment by alex-aizman** [comment]
```log
daemon.go:177 Version 3.11.24dd15eb ...
```

We are at [v3.21](https://github.com/NVIDIA/aistore/releases) right now. Version 3.11 that you are running is not simply old, it is **very** old. I'd suggest to make the transition and use the latest release, if possible.

Secondly and separately: 

Error code 50 above (`sie#50`) corresponds to the following check:
* https://github.com/NVIDIA/aistore/blob/master/volume/vinit.go#L179-L192

I don't think the error code has changed but the code that handles it certainly has (changed). Feel free to give it a shot.
