### ISSUE TITLE
Python sdk put content times out

### ISSUE THREAD

**Issue by satyatumati** [NVIDIA/aistore#168]
When trying to put a 15MB tensor, python sdk timesout using `put_content`

**Comment by gaikwadabhishek** [comment]
Hey Satya,
As we discussed, to debug further we would require log of AIStore. 15MB put should not be a problem at all. There might be an issue in the cluster, some config might be set wrong, or the code is calling the put_content. 

To debug, can you run regular put with a file of 15 MB or more to see if things are still going wrong. You can use `ais cli` or continue on python.

**Comment by satyatumati** [comment]
Figured out this is due to our ssl setup
