### ISSUE TITLE
Promoting an object using python sdk fails

### ISSUE THREAD

**Issue by satyatumati** [NVIDIA/aistore#169]
`client.bucket(bucket).object(path).promote(f"s3://{bucket}/{path}")` fails when trying to promote an object in `s3` to `aistore`

`AISError: STATUS:400, MESSAGE:promoted source must be an absolute path (got "s3://ghost-official-test/satya_aistore/2024-02-13-10-01-40/0")`

**Comment by gaikwadabhishek** [comment]
Hey Satya,
I think you are using `promote` wrong. It is expecting a local path, you are giving it a remote path. Check this test case to have a better idea on how `promote` works - https://github.com/NVIDIA/aistore/blob/b395633faaf7aa81e4fef3574a2357acd4efe5c2/python/tests/integration/sdk/test_object_ops.py#L133-L193

Info on promote - https://aiatscale.org/blog/2022/03/17/promote, https://aiatscale.org/docs/overview#promote-local-or-shared-files
