### ISSUE TITLE
Migration of data between deployments

### ISSUE THREAD

**Issue by satyatumati** [NVIDIA/aistore#172]
### Describe the issue

We have a kubernetes cluster of older aistore 3.11. We decided to deploy a new cluster with latest version of aistore. Is there a way to move the data between deployments?

### Links

na

**Comment by alex-aizman** [comment]
multiple ways to do it but maybe the easiest would be - via backup to Cloud. Incidentally, backup is always a good idea - you are not supposed to have a single copy of any production data. Anyway, example:

```console
$ ais bucket cp ais://src s3://dst
```
This then prints out a message on how to monitor the progress. Once in the data is safely backed up, you can then get rid of 3.11 without any fear. And then deploy v3.22 from scratch.

P.S. As a side, there'd be an interesting exercise to attach - as in: `ais cluster remote-attach` - 3.11 cluster to 3.22 and see if that works. And I can imagine several other things, including vanilla `rsync`. But checking out anything like that will take time that we simply don't have. Hence, Cloud.
