### ISSUE TITLE
Build for arm64

### ISSUE THREAD

**Issue by KhanMechAI** [NVIDIA/aistore#177]
### Describe the feature

I'd like to run this on an NVIDIA Jetson, so an arm64 build would be great. 

### Use Case

Embedded storage

### Proposed Solution

Modify platform specific api's to use generic unix api's

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AIStore build (latest, v3.22, ...)

latest

### Environment details (OS name and version, etc.)

l4t 35.1

**Comment by gaikwadabhishek** [comment]
This feature request will not be prioritized at this time as it does not align with our current goal of scalable storage. Our primary focus is on storing and providing high throughput for petascale deep learning.

While we may consider supporting this feature in the future, our team currently has other objectives that require immediate attention.

**Comment by KhanMechAI** [comment]
I may be able to find some time to try and help, any chance you have a rough idea what might need to be done? Would a naive “fix it till it builds” be ok, or would I need to have a better grasp of the code/design?

**Comment by alex-aizman** [comment]
That'd be awesome if you give it a shot! The first step is crystal clear: port the following few assorted sources to arm64:

```console
$  find . -type f -name "*_linux.go"
./fs/fs_linux.go
./cmn/cos/err_linux.go
./sys/proc_linux.go
./sys/api_linux.go
./sys/mem_linux.go
./sys/cpu_linux.go
./bench/microbenchmarks/nstlvl/drop_caches_linux.go
./ios/diskstats_linux.go
./ios/dutils_linux.go
./ios/fsutils_linux.go
```

In the end, we are supposed to see the same filenames with "_arm" suffix instead of "_linux".

Compare with MacOS port that we do have: ` find . -type f -name "*_darwin.go"`
