### ISSUE TITLE
AuthN support for S3 Compat Clients

### ISSUE THREAD

**Issue by chiefMarlin** [NVIDIA/aistore#181]
Hi,
I am looking for a way to secure access to s3 buckets at http://localhost:51080 -> ais://abc, looking over the below docs i dont see any references on how to do this.
https://github.com/NVIDIA/aistore/blob/main/docs/s3compat.md
https://github.com/NVIDIA/aistore/blob/main/docs/s3cmd.md#2-how-to-have-s3cmd-calling-ais-endpoint

I have also tried adding authn server however that still permits access with any supplied credentials when testing with aws cli.

Purpose is to use aistore as s3 server and access it with s3 compatible clients.

Thanks

**Comment by gaikwadabhishek** [comment]
Hey @chiefMarlin,

Are you running the AIStore cluster locally? If so, have you configured AIStore with an AWS backend? When prompted during the `make deploy` process, make sure to select `y` for AWS integration. This setup will automatically use the AWS credentials stored in your `.aws/` directory.

To list all remote buckets, you can use the following command:

```sh
$ ais ls --all
```

**Comment by alex-aizman** [comment]
just out of curiosity - what are you trying to do? Asking also because all-in-one docker image that we provide is there mostly for first-time users (e.g., to play with [CLI](https://github.com/NVIDIA/aistore/blob/main/docs/cli.md) and demonstration purposes.

**Comment by chiefMarlin** [comment]
Hi Alex,
I've only discovered this project yesterday and so far im testing out the basic features set, next up is scaling across servers/mirror and stress testing. My use case is primarily to replace MinIO as s3 server, as part of that im hoping to have it scale across multiple machines within same dc. I am also interested in seeing how well geo mirroring works.

**Comment by gaikwadabhishek** [comment]
Hey @chiefMarlin,

To access local ais buckets on a s3 compatible client, append `/s3` to the URL—this should work perfectly.

Here's what I did to verify:

I had a cluster running with both `S3` and `AIS` buckets. Using the AWS CLI, I was able to access it as follows:

```bash
$ aws s3 ls --endpoint=http://<aistore-endpoint>:51080/s3
# This lists all S3, GCP, and AIS buckets

$ aws s3 ls <ais-bucket-name> --endpoint=http://<aistore-endpoint>:51080/s3
# This lists all objects within that specific AIS bucket
```

Let me know if you run into any issues!

**Comment by chiefMarlin** [comment]
@gaikwadabhishek @alex-aizman 
I am looking to add authentication to the s3 access to prevent anyone and everyone from accessing any bucket they want. This is a trivial feature that any s3 server comes with.
In all of the examples provided, including yours, no authentication for s3 buckets are required and i dont see any mention on how to enable this.
As i mentioned, i tried adding authn server and that worked for securing access using "ais" tool but not compat s3 client.

I hope this clears it up.

**Comment by gaikwadabhishek** [comment]
I see. I tried it myself and debugged a bit - 

```
s3cmd --debug ls s3://nnn --add-header="Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwaXJlcyI6IjIwMjQtMDgtMTBUMTA6NDY6MzQuMjk1MDA3NTIyLTA3OjAwIiwidXNlcm5hbWUiOiJhZG1pbiJ9.gS2JNSzCYcxuhu8hkIVA41Chi1kG1O-Rtb1pxOgilE4"
```
This doesn't work as s3cmd is not allowing me to change the Authorization header -
```
DEBUG: Response:
{'data': b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>Authorizatio'
         b'nHeaderMalformed</Code><Message>The authorization header is malforme'
         b"d; the region 'us-east-1' is wrong; expecting 'ap-southeast-1'</Mess"
         b'age><Region>ap-southeast-1</Region><RequestId>A9CXDVTCWHW1GF0J</Requ'
         b'estId><HostId>Pq/VO2hy1s+23GBhVKXqL9j1DBYTFXjAqW+aLB2i3j6z6jxU8Ah/dE'
         b'WfJaguRdL3p9PhpXvOQnA=</HostId></Error>',
 'headers': {'connection': 'close',
             'content-type': 'application/xml',
             'date': 'Fri, 09 Aug 2024 18:04:30 GMT',
             'server': 'AmazonS3',
             'transfer-encoding': 'chunked',
             'x-amz-bucket-region': 'ap-southeast-1',
             'x-amz-id-2': 'Pq/VO2hy1s+23GBhVKXqL9j1DBYTFXjAqW+aLB2i3j6z6jxU8Ah/dEWfJaguRdL3p9PhpXvOQnA=',
             'x-amz-request-id': 'A9CXDVTCWHW1GF0J'},
 'reason': 'Bad Request',
 'status': 400}

```

This will require a fix on s3cmd side or we will need to work on some changes on the aistore side. We are open to suggestions let us know if you could help us on this one.

**Comment by gaikwadabhishek** [comment]
Hey @chiefMarlin,

Apologies for the delay—we were tied up with other features but finally got some time to work on this. We've updated the S3 compatibility code in AIStore to handle AuthN.

To use it with S3CMD, check out the instructions here: [S3CMD with AIStore Authentication](https://github.com/NVIDIA/aistore/blob/main/docs/s3cmd.md#s3cmd-with-aistore-authentication-authn).

For Boto, the setup guide is here: [Boto3 with AIStore Authentication](https://github.com/NVIDIA/aistore/blob/main/python/aistore/botocore_patch/README.md#boto3-with-aistore-authentication).

**Comment by chiefMarlin** [comment]
> Hey @chiefMarlin,
> 
> Apologies for the delay—we were tied up with other features but finally got some time to work on this. We've updated the S3 compatibility code in AIStore to handle AuthN.
> 
> To use it with S3CMD, check out the instructions here: [S3CMD with AIStore Authentication](https://github.com/NVIDIA/aistore/blob/main/docs/s3cmd.md#s3cmd-with-aistore-authentication-authn).
> 
> For Boto, the setup guide is here: [Boto3 with AIStore Authentication](https://github.com/NVIDIA/aistore/blob/main/python/aistore/botocore_patch/README.md#boto3-with-aistore-authentication).

Hi,
I noticed that the instructions me ntion to modify the s3cmd, does the auth not work with any other s3 compatible client ?

**Comment by gaikwadabhishek** [comment]
@chiefMarlin its a small patch. 

```
pip uninstall s3cmd
# clone the project, add the line 
python setup.py install
```

I tried multiple things, all clients sign the request and put the info in `Authorization` hdr, even if you add it after the signing of the request it will be replaced. 

`botocore` patch is much cleaner, you add a header on a specific event. 

You just need the hdr - `Authorization` with `Bearer <token>` that's all. 

If you find a cleaner way, please let us know

**Comment by gaikwadabhishek** [comment]
We also considered changing or adding a new Hdr called `Ais-Authorization`, but it would just add more complexity and management efforts. We pull PBs every week in our deployments. Even small checks eventually add up. 

I have the diff - 
```
diff --git a/api/apc/headers.go b/api/apc/headers.go
index bba4bb703..d1720fa05 100644
--- a/api/apc/headers.go
+++ b/api/apc/headers.go
@@ -81,6 +81,7 @@ const (
 // AuthN consts
 const (
 	HdrAuthorization         = "Authorization" // https://developer.mozilla.org/en-US/docs/Web/HTTP/Hdrs/Authorization
+	HdrAisAuthorization      = aisPrefix + HdrAuthorization
 	AuthenticationTypeBearer = "Bearer"
 )
 
diff --git a/cmd/authn/tok/token.go b/cmd/authn/tok/token.go
index cc19708d0..4513408b6 100644
--- a/cmd/authn/tok/token.go
+++ b/cmd/authn/tok/token.go
@@ -59,17 +59,37 @@ func JWT(expires time.Time, userID string, bucketACLs []*authn.BckACL, clusterAC
 	return t.SignedString([]byte(secret))
 }
 
-// Header format: 'Authorization: Bearer <token>'
+// Header format: 'Authorization: Bearer <token>' or 'Ais-Authorization: Bearer <token>'
 func ExtractToken(hdr http.Header) (string, error) {
-	s := hdr.Get(apc.HdrAuthorization)
-	if s == "" {
-		return "", ErrNoToken
+	var err error
+
+	extract := func(authHeader string) (string, error) {
+		if !strings.HasPrefix(authHeader, apc.AuthenticationTypeBearer+" ") {
+			return "", ErrNoBearerToken
+		}
+		return strings.TrimPrefix(authHeader, apc.AuthenticationTypeBearer+" "), nil
 	}
-	idx := strings.Index(s, " ")
-	if idx == -1 || s[:idx] != apc.AuthenticationTypeBearer {
-		return "", ErrNoBearerToken
+
+	// Try 'Authorization' header first
+	if s := hdr.Get(apc.HdrAuthorization); s != "" {
+		token, err := extract(s)
+		if err == nil {
+			return token, nil
+		}
 	}
-	return s[idx+1:], nil
+
+	// Fallback to 'Ais-Authorization' header
+	if s := hdr.Get(apc.HdrAisAuthorization); s != "" {
+		return extract(s)
+	}
+
+	// If no 'Bearer' in `Authorization` and `Ais-Authorization` header missing
+	if err == ErrNoBearerToken {
+		return "", err
+	}
+
+	// No valid token found
+	return "", ErrNoToken
 }
```

**Comment by chiefMarlin** [comment]
@gaikwadabhishek
I am using aws-sdk-go-v2 and other open-source S3-compatible clients, not s3cmd. It seems you missed my main question: does this authentication method fail across other S3-compatible clients too? Your suggestion of patching botocore feels like a workaround rather than addressing the root of the issue. This solution doesn’t seem suitable for broader compatibility. Can you suggest a more sustainable approach that works across different clients?

**Comment by gaikwadabhishek** [comment]
@chiefMarlin 

I'm not quite following your point. If you're using `aws-sdk-go-v2`, why not directly use the Go APIs of AIStore?

> *"Does this authentication method fail across other S3-compatible clients too?"*

It really depends on the client. Each S3-compatible client constructs requests differently. The bottom line is that if AIStore has authentication enabled, the request needs to include an `Authorization` header with `Bearer <token>`.

> *"Your suggestion of patching botocore feels like a workaround rather than addressing the root of the issue."*

Could you elaborate on what you see as the "root of the issue"? How would we be responsible for the inability of various S3 clients to send an `Authorization` header? Each client has its own request-handling logic, which makes sense. For more details on the `Authorization` header, see: [MDN: Authorization Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization).

> *"Can you suggest a more sustainable approach that works across different clients?"*

We had two ideas in mind:
1. **Support for an additional `Ais-Authorization` header**: We analyzed this option, but since the header check would be needed for every request made to AIStore with authentication enabled, the overhead was deemed too costly.
2. **Replace the `Authorization` header with `Ais-Authorization`**: This option didn't align with standard practices. We want to adhere to the standard use of the `Authorization` header, as outlined here: [MDN: Authorization Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization).

**Comment by chiefMarlin** [comment]
@gaikwadabhishek, I've repeatedly highlighted that my goal is to use AIStore as an S3-compatible server, as advertised on your page: [REST API. Comprehensive native HTTP-based API, as well as compliant Amazon S3 API to run unmodified S3 clients and apps](https://aistore.nvidia.com) Suggesting I use the AIStore SDK or patch the client misses the point. Switching to use Go APIs of AIStore would require a complete code rewrite, which I'm trying to avoid. Given the situation, exploring alternatives like MinIO seems more practical. Thanks for your time.

**Comment by alex-aizman** [comment]
> Switching to use Go APIs...

That's a native API available via Go and Python. In our experience, switching from S3 client (of any kind) to using our Python SDK takes little to no time.

Secondly and separately:

By definition, design, and motivation, AIS equally supports 3 (three) Clouds, including Amazon. We may, and likely will, add more backends in the future. We are not a drop-in replacement for Amazon S3 - never claimed to be, exceptions disclosed and documented in the s3compat.md table. The motivation is totally different.
