### ISSUE TITLE
AiStore.org

### ISSUE THREAD

**Issue by Cooldomainer** [NVIDIA/aistore#183]
### Describe the feature

Hi, I am the owner of AiStore.org

I saw your project and am very enthusiastic of it. I am reaching out because I thought perhaps you were interested in getting the name AiStore.org which clearly matches your brand name 

Let me know 
Kinds Regards
Pier

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AIStore build (latest, v3.22, ...)

latest

### Environment details (OS name and version, etc.)

X

**Comment by alex-aizman** [comment]
This is a violation of the code of conduct.
