### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by johnzielke** [NVIDIA/aistore#184]
What is the appropriate way to disclose security related issues for this repository? I was unable to find a security policy.

**Comment by gaikwadabhishek** [comment]
Hi @johnzielke,

We currently don't have a security policy in place, but I'll be setting one up shortly. Could you please send us the relevant details at [ais@exchange.nvidia.com](mailto:ais@exchange.nvidia.com)?

Once you've sent the email, kindly notify us here.

Thank you!

**Comment by johnzielke** [comment]
Thank you, I have now sent the email to the provided address

**Comment by gaikwadabhishek** [comment]
Hey @johnzielke ,
For some reason, the NVIDIA network is blocking external emails on the distribution list that I had mentioned. Can you please forward it to my email - gaikwadabhishek1997@gmail.com

Sorry, for the inconvenience

**Comment by johnzielke** [comment]
No worries, I resent the email to the mentioned email

**Comment by alex-aizman** [comment]
Hi John

Thanks for your investigation and the write-up you sent us - it is impressive. Currently, we position aistore for production deployments in trusted data-center environments, behind a firewall, where we have other means to control who-accesses-what. But of course, the work is going on to deliver the Option 2. If you want to give it a hand in some shape or form, we'd welcome that - aistore is open source.

**Comment by johnzielke** [comment]
Thank you very much. I suspected as much and don't think it has a huge impact on any of the installations currently in use. Nevertheless, since the functionality with authorization using ACLs etc is documented, IMHO this is something that could be added as a limitation to the documentation. And especially the ACL portion cannot easily be secured using ip/port firewall rules, but would need application firewalls, which probably would be not desirable for performance reasons. I'm happy to help and will see if I can find the time to work on a PR. But of course wanted to first make sure I understand the architecture correctly and get your feedback.

**Comment by gaikwadabhishek** [comment]
> What is the appropriate way to disclose security related issues for this repository? I was unable to find a security policy.

https://github.com/NVIDIA/aistore/blob/main/SECURITY.md I have added a security policy as well. Thanks @johnzielke
