### ISSUE TITLE
How do I start an cluster with a particular config?

### ISSUE THREAD

**Issue by rachtsingh** [NVIDIA/aistore#192]
### Describe the issue

I've looked through the documentation and tried a few things but I cannot figure this out - can someone help me understand?

I have a server on which I want to deploy AIS (let's say I want a proxy and target node for now, but later it might just be proxy). I wanted to limit the resources that AIS uses, especially memory, since the server is used for other things as well. I created a file `ais_local.json` in a folder  (along with `ais.json`), and I want to point it to use a specific disk (mounted as `/aistore`).

But after reading the Getting Started documentation page a few times and trying things, I cannot figure out how to start a cluster with either `make deploy`, `clean_deploy.sh`, or `aisnode` directly. What is the right command?

I want to keep a separate (version controlled) config because I want backups of the configuration.

For what it's worth this practice of using shell scripts for all launch processes is very, very confusing. I'm not entirely sure why you cannot launch a new cluster using just the `ais` command. Did I just miss how to do that? Why is "make clean" used repetitively (I assume once you make the "ais" and "aisnode" binaries, there's no reason to delete them)? Why is "kill" a make target rather than an `ais` command? 

Thank you for the software - it looks very promising and I'm excited to use it, but I would love some help figuring it out.

### Links

https://aiatscale.org/docs/getting-started

**Comment by alex-aizman** [comment]
`make clean`, `make deploy`, etc. is all about development. For production, we usually use Kubernetes - the last row in this table:

*  https://github.com/NVIDIA/aistore/tree/main/deploy

also note: support questions will likely take us a long time to respond, if at all

not an issue - closing
