### ISSUE TITLE
Disable auto rebalancing for a dynamic cluster

### ISSUE THREAD

**Issue by xiang90** [NVIDIA/aistore#195]
### Describe the feature

Add a configuration to disable auto cluster-wide rebalancing. Maybe this is already supported with some configuration?

### Use Case

In our environment, machines are highly dynamic. We aim to use AI Store as a best-effort S3 read cache. 

Our primary goals are as follows:
- Handle Offline Machines Gracefully: When a machine goes offline, we want to avoid triggering a global rebalancing event. Such rebalancing can degrade performance unnecessarily, especially when there is no change in the workload.
- Optimize for New Machines: Conversely, when a new machine comes online, we want it to actively participate in caching future reads without triggering an instant cache filling. This ensures that the cache progressively adapts to include the newly added machine without disrupting the existing workload.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AIStore build (latest, v3.22, ...)

Latest

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by alex-aizman** [comment]
```console
ais config cluster rebalance.enabled false
```

Tips:

```console
ais config cluster | grep rebalance
```

```console
git grep "rebalance.*disable"
```

Closing - not an issue

**Comment by xiang90** [comment]
@alex-aizman 

Thanks!

A followup question: If we disable rebalance, the new cache data will fill into the machine with the lowest data usage (new machine)?
