### ISSUE TITLE
[Question] AIStore+WebDataset and AWS SageMaker

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/aistore#66]
Hi, do you happen to know offhand of any technical blockers in using AIStore+WebDataset with AWS SageMaker and S3 or EFS mount?

**Comment by VirrageS** [comment]
Hey, could you give a bigger picture on how you plan to do it? I don't have any experience with SageMaker.

**Comment by austinmw** [comment]
Hi @VirrageS thanks for your response. I'd like to use SageMaker's Pipe Mode:
"In Pipe-mode, data is pre-fetched from S3 at high-concurrency and throughput and streamed into Unix Named Pipes (aka FIFOs) - one FIFO per Channel per epoch"
Here's a link with a minimum example of how Pipe Mode reads from S3 if you have the time to check it out:
https://github.com/aws/amazon-sagemaker-examples/blob/6d2ed2833ce887b6d0f79354e221daccc5422405/advanced_functionality/pipe_bring_your_own/train.py#L46

**Comment by VirrageS** [comment]
I see, so if I understand correctly you will be using AIStore as S3 client. Is that correct? If so, I don't think there should be any difficulties as far for this. There are couple small things that would be required to make AIStore fully compatible S3 client but the core functionality is there ready to be used.

**Comment by austinmw** [comment]
Yes that's been my initial plan, though I haven't delved deep into the AIStore documentation yet to fully understand it. Thanks I appreciate your help!

**Comment by VirrageS** [comment]
Makes sense :) Let us know if you stumble upon any issues.

**Comment by austinmw** [comment]
Hi @VirrageS , I've just installed the ais cmdline tool, but in my AWS SageMaker terminal when I run `ais ls ais://` I get the error:

> AIStore proxy unreachable at http://127.0.0.1:8080. You may need to update environment variable AIS_ENDPOINT

How should I set this?
