### ISSUE TITLE
ETL documentation issue

### ISSUE THREAD

**Issue by kittipatv** [NVIDIA/aistore#69]
Hi team,

I think [ETL](https://nvidia.github.io/aistore/docs/etl) documentation needs to be updated. Specifically, I would like to learn more about how to write transform function. There is the following sentence in the doc, but I don't find the example.

> You can write your own custom transform function (see example below) that takes input object bytes as a parameter and returns output bytes (the transformed object’s content).

**Comment by knopt** [comment]
Hello there,

Thank you for pointing out the issue!

The step-by-step guides can be found in the [Playbooks](https://nvidia.github.io/aistore/docs/playbooks) directory.

Specifically, the [ImageNet example](https://nvidia.github.io/aistore/docs/playbooks/etl/etl_imagenet_pytorch) provides a step-by-step ImageNet preprocessing tutorial, with `build` request. Additionally, we have prepared the [ETL Getting Started](https://www.youtube.com/watch?v=4PHkqTSE0ls]) video which should help you with the process.

In the meantime, we will work on improving the documentation, so the resources are easily accessible and readable. If you happen to have any more questions or requests, feel free to comment on this issue or create a new one.

Thanks!
Tomasz
