### ISSUE TITLE
When deploy ais to k8s cluster with network policy ais cluster never be ready.

### ISSUE THREAD

**Issue by and-1** [NVIDIA/aistore#72]
I use calico network policy and it drops traffic to service while no endpoints, so in bootstrap phase curl tries to connect to service and wait until reach default timeout (5m). Readiness probe couldn't get success because pod restart. Also it applicable to ais_docker_start script - primary proxy restarts because targets aren't connected to proxy(curl in target pod wait). Please, set curl timeout in ais_readiness.sh and ais_docker_start.sh scripts like that `--connect-timeout 3`

**Comment by VirrageS** [comment]
Thanks for the suggestion we will soon push the fix!

>  drops traffic

If it drops traffic, then should the `curl` immediately finish? It's weird that it waits default timeout.

**Comment by VirrageS** [comment]
Should be fixed with https://github.com/NVIDIA/aistore/commit/bbe290377f1a0cb65bea0fced44f22c3be88e250. Included in updated `aistore/aisnode:latest` image.
