### ISSUE TITLE
Docs about python client is missing

### ISSUE THREAD

**Issue by diggerdu** [NVIDIA/aistore#78]
Thanks for your wonderfull work. But I wonder why the documents about [python client](https://github.com/NVIDIA/aistore/blob/master/docs/overview.md#python-client) is missing. Is the developing of python client still in progress?

**Comment by VirrageS** [comment]
The Python client that we previously had was automatically generated but it was really hard to maintain and not very user friendly. We decided to drop it. In a meantime we wanted to create our own Python client with new features. We have some very initial work done in https://github.com/NVIDIA/ais-etl/blob/master/client/ais_tar2tf/aisapi.py. But there are just couple of API requests we wanted to use in other project, so it is very minimal and in the future the structure will probably change.

We have plans to revive the Python client work and provide convenient adapters for PyTorch and TensorFlow. Unfortunately at this point we didn't have much time to work on this. In meantime, I will remove the reference in the docs as it doesn't point to anything.

Thanks for the interest and the comment. We will take this into consideration in our planning!

**Comment by VirrageS** [comment]
I've just pushed commit which removes the Python client reference - but we will try to work on the Python client in the near future!

Unless there is something else I will be closing this issue.
