### ISSUE TITLE
Aistore HTTP failed to json-unmarshal GET request

### ISSUE THREAD

**Issue by Luab** [NVIDIA/aistore#80]
Hi,

I am running aistore as single docker deployment + ais cli on host machine to monitor and play around. 
Currently, I am trying to list all buckets from my deployment using an example from http_api, but the command fails with HTTP 400 error code
```
luab@datastore:~$ curl -L -X GET 'http://localhost:8080/v1/buckets'
{"status":400,"message":"failed to json-unmarshal GET request, err: EOF [*cmn.ActionMsg](proxy.go, #384)","method":"GET","url_path":"/v1/buckets","remote_addr":"172.17.0.1:60062","caller":""}
```
Same for 
```
luab@datastore:~$ curl -L -X GET 'http://localhost:8080/ais/medical'
{"status":400,"message":"invalid protocol scheme ''","method":"GET","url_path":"/ais/medical","remote_addr":"172.17.0.1:60070","caller":""}
```

At the same time ais cli commands seem to work just fine 
```
luab@datastore:~$ ais bucket ls
AIS Buckets (2)
  ais://arxiv
  ais://medical
```
I am also able to retrive node config using this command. 
```
luab@datastore:~$ curl -X GET http://localhost:8080/v1/daemon?what=config
```

Am I doing requests wrong or is something broken is aistore/my setup? Thanks!

**Comment by VirrageS** [comment]
Closing this issue. If you have further questions or problems, let us know :) !
