### ISSUE TITLE
Rebalance too slow

### ISSUE THREAD

**Issue by and-1** [NVIDIA/aistore#84]
Hi! I'm trying restore missing data using rebalance in ec bucket (about 3500000 objects). This process takes too long time, after 24 hours ais restored only about 100 000 object. ec.batch_size set to max (128). How do i decrease rebalance time?

ais version - 3.5

**Comment by VladimirMarkelov** [comment]
Hi!

Yes, rebalance with EC enabled may be way slow.

If you only want to restore missing object it is faster to just read all objects one by one. This way restores missing objects and data/parity slices of the restored objects, but does not restore missing slices.

In newer versions of AIS the rebalance is much faster, but it does not restore anything.

**Comment by and-1** [comment]
THX! The reading all object is quite fast way to restore files!
