### ISSUE TITLE
Damaged metafile after update from 3.5 to 3.6

### ISSUE THREAD

**Issue by and-1** [NVIDIA/aistore#85]
After update to 3.6 version i see error in targets log:
`W 22:24:01.281820 ec.go:440 failed to load metadata from "/ais/sda/@ais/nvais/%mt/0025f/bJgGysbPLgSoXmVEsZVjMzcefFbWKebg": damaged metafile "/ais/sda/@ais/nvais/%mt/0025f/bJgGysbPLgSoXmVEsZVjMzcefFbWKebg": unsupported metadata format version 2065855337. Only 1 supported`
How can i resolve this problem and covert to new metadata format. Maybe exist update documentation?

**Comment by and-1** [comment]
Any updates?

**Comment by VirrageS** [comment]
Hey @and-1, so sorry for the delay. Unfortunately there is nothing you can do to repair those objects. This particular change is not forward, nor backward compatible. So the only way to do it would be to restore all objects, disable EC on the bucket, upgrade the AIS, and the enable EC again.

Sorry for the inconvenience that this change has caused.
