### ISSUE TITLE
support Aliyun oss

### ISSUE THREAD

**Issue by Liberxue** [NVIDIA/aistore#90]
- [ ] [Aliyun oss](https://www.alibabacloud.com/product/object-storage-service)

**Comment by VirrageS** [comment]
This looks really interesting. Seems like Aliyun OSS has Go SDK so it should be pretty straightforward to set it up.

But currently we don't have access to Alibaba Cloud and not sure if we have enough time to look at it. Are you willing to add support for it?

**Comment by Liberxue** [comment]
yeah
I've been a little busy lately and need a little time，
I'll get it done.

**Comment by VirrageS** [comment]
Sounds good, thanks!
