### ISSUE TITLE
Query on  aistore.pytorch.Dataset

### ISSUE THREAD

**Issue by KavyaPuranik** [NVIDIA/aistore#95]
Hi,

I'm following this doc to train Imagenet Dataset: `https://github.com/NVIDIA/aistore/blob/cc6e029721ef159f3df516ec9f8e3065ef6ac54d/docs/_posts/2021-10-22-ais-etl-2.md` 

I've a query specifically related to this part. 
`train_loader = torch.utils.data.DataLoader(
    aistore.pytorch.Dataset(
        "http://aistore-sample-proxy:51080", # AIS IP address or hostname
	Bck("imagenet"),
        prefix="train/", transform_id="my-first-etl",
        transform_filter=lambda object_name: object_name.endswith('.jpg'),
    ),
    batch_size=args.batch_size, shuffle=True,
    num_workers=args.workers, pin_memory=True)`

I see a type error, when I try to use it as is in the training code. `pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)` Do you any insights on how to mitigate this error?

Also I found that the implementation of  `aistore.pytorch.Dataset` is present in one of the development branch(post-3).

**Comment by gaikwadabhishek** [comment]
Hi Kavya,
I see you were trying to use the AIS implementation of Dataset.

**Comment by gaikwadabhishek** [comment]
Check this https://github.com/NVIDIA/aistore/blob/master/sdk/python/aistore/pytorch/aisio.py

**Comment by KavyaPuranik** [comment]
Hi,

I was able to resolve the issue by making use of webdataset. I'll try out the fileloader approach as well.  

I have couple of other queries related to aistore etl. I have a usecase where in I'm trying to offload the dataset preprocessing part to etl. Will you be able to provide support for etl in the python client?

**Comment by gaikwadabhishek** [comment]
Hi @KavyaPuranik 
https://pypi.org/project/aistore/1.0.3 

The latest Python SDK release contains APIs related to ETL. 

Documentation and Usage:  
https://aiatscale.org/docs/python-api#etl
https://github.com/NVIDIA/aistore/blob/master/sdk/python/README.md#etls
https://github.com/NVIDIA/aistore/blob/master/sdk/python/sdk-etl-tutorial.ipynb
