### ISSUE TITLE
aisfs problems

### ISSUE THREAD

**Issue by tmbdev** [NVIDIA/aistore#99]
I can't get `aisfs` to work.

- it does not seem to respect configuration files in `$HOME/.config/ais/bucket.aisfs.mount.json`
- there is now way of telling what configuration file it is actually loading
- it ignores AIS_ENDPOINT

I would suggest the following:

- aisfs should use the same defaults that are configured for ais (including ~/.config/ais and environment variables)
- with those defaults, `aisfs bucket dir` should just work
- there should be a `-v` option that logs the operations (reading config file, contacting server, mounting, etc.) to stderr
- there should be a `--configfile` option that lets users provide a config file on the command line

I'd also suggest adding actual subcommands:

- aisfs mount bucket dir
- aisfs umount dir
- aisfs stats dir
- ais config  -- displays current config, including where loaded

**Comment by alex-aizman** [comment]
```sh
# go test -v -tags=debug
=== RUN   TestE2E
Running Suite: TestE2E
======================
Random Seed: 1657561794
Will run 4 of 4 specs

^C
Ran 1 of 1 Specs in 0.680 seconds
FAIL! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
exit status 1
FAIL    github.com/NVIDIA/aistore/cmd/aisfs/test        0.769s
# ll ~/.config/ais/aisfs
total 12
drwxr-x--- 2 root root 4096 Jul 11 13:49 ./
drwxr-xr-x 3 root root 4096 Jul 11 13:49 ../
-rw-r----- 1 root root  335 Jul 11 13:49 dGvIbWnzGO.aisfs.mount.json
```

But still, `aisfs` is purely experimental and currently I have plans to productize it. Closing the ticket.

**Comment by alex-aizman** [comment]
as above
